### ISSUE TITLE
Device is not registered in Tuya Cloud

### ISSUE THREAD

**Issue by fischmuc** [PlusPlus-ua/ha_tuya_ble#48]
BLE Irrigation Valve is identified, registered with  Tuya IoT, but prompts this error message in the end:
<img width="436" alt="image" src="https://github.com/PlusPlus-ua/ha_tuya_ble/assets/66817302/f097b2be-dcbb-4e31-a3f0-0f0820e7e429">

Device is in the list but shows offline:

<img width="731" alt="image" src="https://github.com/PlusPlus-ua/ha_tuya_ble/assets/66817302/32169777-aef5-4307-abf3-ae9cb78a5e6d">

Any thoughts? Thank you.

Saw #19 but couldn't resolve the issue for me.

**Comment by fischmuc** [comment]
Solved: Created a new Smart Life App Account, linked the new App Account to the project on IoT Platform

**Comment by pilonull** [comment]
> Solved: Created a new Smart Life App Account, linked the new App Account to the project on IoT Platform

Just out of curiosity, because I am facing this same issue... After creating a new smart life account, did your device show as online in the IOT cloud platform? Or was it still offline but started working the the HA tuya BLE integration? 

I created a new tuya account, linked the device (SGS01 soil sensor) to the app logged in with the new account, then added that to the IOT cloud dev account, but device is still showing offline and when I add it to HA it doesn't get any entities other than the signal strength one.

**Comment by markusg1234** [comment]
> > Solved: Created a new Smart Life App Account, linked the new App Account to the project on IoT Platform
> 
> Just out of curiosity, because I am facing this same issue... After creating a new smart life account, did your device show as online in the IOT cloud platform? Or was it still offline but started working the the HA tuya BLE integration?
> 
> I created a new tuya account, linked the device (SGS01 soil sensor) to the app logged in with the new account, then added that to the IOT cloud dev account, but device is still showing offline and when I add it to HA it doesn't get any entities other than the signal strength one.

I have the SGS01 sensor and it works. 
I couldn't find a fork that would work so I used https://github.com/PlusPlus-ua/ha_tuya_ble/pull/88 and created my own fork.

Note: I haven't added any other newer devices that other forks have added. 

https://github.com/markusg1234/ha_tuya_ble
